### ISSUE TITLE
New Pypi release?

### ISSUE THREAD

**Issue by KarelJakubec** [kyrus/python-junit-xml#43]
Hi @brianebeyer,
or whoever has access to Pypi for junit-xml. :) Would it be possible to make a new release? The previous one is almost one year and as far as I see there are a few new features (which I would like to use :) ).

Thanks, best
Karel

**Comment by mr-c** [comment]
Yes, this would be great -- thank you!

**Comment by brianebeyer** [comment]
Sorry everyone, it took forever to find the credentials I used with pypi. I've bumped the version to 1.8 and uploaded to pypi. All set?

**Comment by KarelJakubec** [comment]
Thanks! :heart:

**Comment by rasjani** [comment]
1.8 seems to have quite a lot of bugs regarding testing if certain attributes are there or not .. For example, if i pass a timestamp to testsuite, log and url properties will be logged as "None" .. These seem to be fixed in the HEAD and installing from git aint big issue but, would be nice to have those still fixed in pypi..
