### ISSUE TITLE
1.9 only published as a wheel on PyPi 

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [kyrus/python-junit-xml#69]
The 1.9 release on PyPi is not available as an sdist, only as a wheel. Providing both would be wonderful, to make it easier to distributions to update to the new versions.

**Comment by dtrodrigues** [comment]
`cfn-lint` in macOS homebrew depends on `junit-xml` version 1.9, but since the 1.9 PyPI release doesn't include the source, it's relying on a fixed commit of this repository on GitHub instead of an official release in PyPI.

**Comment by Anthchirp** [comment]
this is also the reason there is no release on conda-forge

**Comment by chenrui333** [comment]
Any update on this thread? Thanks!

**Comment by chenrui333** [comment]
as the artifact is put on pypi, this can be closed now.

![image](https://user-images.githubusercontent.com/1580956/214400653-c1f576f7-2342-4d04-a8c4-7d579fef94e5.png)

**Comment by s-t-e-v-e-n-k** [comment]
Wonderful!

**Comment by musicinmybrain** [comment]
Tagging the release here on GitHub would be great too. As the maintainer of the [Fedora Linux package](https://src.fedoraproject.org/rpms/python-junit_xml), I need to use a GitHub source archive if I want to run the tests (because the PyPI sdist doesn’t include them), and I have to guess at the commit that corresponds to the PyPI release.
